"""account on delete set null

Revision ID: 479f5851e394
Revises: 1d93c9f9f506
Create Date: 2015-02-10 18:53:05.347618

"""

# revision identifiers, used by Alembic.
revision = '479f5851e394'
down_revision = '1d93c9f9f506'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.drop_index('account_ibfk_10', table_name='account')
    op.drop_index('full_body_id_fk', table_name='message')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('full_body_id_fk', 'message', ['full_body_id'], unique=False)
    op.create_index('account_ibfk_10', 'account', ['default_calendar_id'], unique=False)
    ### end Alembic commands ###
